# -*- coding: utf-8 -*-
"""ultrasound_model.ipynb

Automatically generated by Colaboratory.

filename: ultrasound_model.py
author: Supriya Sudarshan
version: 17.04.2021
description: Covid-19 Detection in ultrasound images using Transfer Learning (VGG19)
"""

# Basic imports
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns
from glob import glob

from tensorflow.keras.models import Model, load_model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator

import sys
sys.path.append('/content/drive/MyDrive/Colab Notebooks')

# user defined
from generic_model import *

# Load data paths

covid_path = '/content/drive/MyDrive/Colab Notebooks/Ultra-sound dataset/batch/Covid'
normal_path = '/content/drive/MyDrive/Colab Notebooks/Ultra-sound dataset/batch/Normal'

# Use glob to grab images from path 
covid_files = glob(covid_path + '/*')
normal_files = glob(normal_path + '/*')

# process image and split it into train and test set
[X_train, X_test, y_train, y_test] = split_images_and_process(covid_files, normal_files)

# Base model: VGG19 - Flatten - FC layer (64 neurons, relu) - Dropout (0.2) - Output(2, softmax)
# Optimizer - Adam, Learning rate - 10-5 
# Loss - binary_crossentropy
# metrics - accuracy

model = vgg_model(lr=1e-5, dropout_val=0.2, fc_neurons=64)

model.summary()

# Data Augmentation on Training Set

train_aug = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True
)

# Batch size (bs) = 2
# Epochs = 100
# Early stopping to stop training when a 'val_loss' has stopped improving for 10 consecutive epochs.

bs = 2
epoch = 100

callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=5, verbose=0)

hist = model.fit(train_aug.flow(X_train, y_train, batch_size = bs),
                    validation_data=(X_test, y_test),
                    callbacks = callback,
                    validation_steps=len(X_test) // bs,
                    steps_per_epoch=len(X_train) // bs,
                    epochs = epoch)

plot_model_acc_loss(history = hist, title = 'Model Accuracy/Loss')

model.save('/content/drive/MyDrive/Colab Notebooks/saved_models/ultrasound_vggmodel.h5')

# Evaluation

y_pred = model.predict(X_test, batch_size=bs)

# Convert to binary classes
y_pred_bin = np.argmax(y_pred, axis=1)
y_test_bin = np.argmax(y_test, axis=1)

# Confusion matrix
print('Confusion Matrix without Normalization')
plot_confusion_matrix(['COVID','NonCOVID'],y_test_bin, y_pred_bin)

print(classification_report(y_test_bin, y_pred_bin))

report(y_test_bin, y_pred_bin)

"""For a dataset consisting of 386 Normal and 324 Covid images:

Covid: Precision = 0.98, Recall = 0.98, F1 Score = 0.98  
Normal: Precision = 0.99, Recall = 0.99, F1 Score = 0.99  

Average F1 Score: 0.99

Confusion matrix: [[64, 1][1, 77]]
"""



"""As per the paper for 226 Normal and 455 Covid findings:

Covid : Precision = 0.99, Recall = 0.97, F1 Score = 0.98  
Normal: Precision = 0.94, Recall = 0.98, F1 Score = 0.96  

Average F1 score: 0.99  

Confusion matrix: [[91, 1]
                    [1, 44]]
"""

